version: 2

# these act as configuration variables or "functions"
# - based on github.com/android/android-ktx/.circleci/config.yml - on 20180208
references:
  workspace: &workspace
    ~/repo

  # android configuration
  config_android: &config_android
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb

  # gcloud configuration
  config_gcloud: &config_gcloud
    working_directory: *workspace
    docker:
      - image: google/cloud-sdk:latest
    environment:
      TERM: dumb

  # cache key configuration to speed up rebuilds
  cache_key: &cache_key
    key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: .
      paths:
        - ftl-tests
        - build
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace

# actual jobs
jobs:

  # basic build, test, save artifacts
  build:
    <<: *config_android

    steps:
      - checkout
      - *restore_cache

      # assemble project
      - run:
          name: Compile
          command: ./gradlew assemble assembleAndroidTest --no-daemon
      - store_artifacts:
          path: build/outputs/aar
      - store_artifacts:
          path: build/libs
      - store_artifacts:
          path: build/distributions/

      # run all checks
      - run:
          name: JVM Tests & Lint
          command: ./gradlew check --no-daemon
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/test-results
      - store_artifacts:
          path: build/reports/lint-results.html
      - store_test_results:
          path: build/reports

      - *save_cache

      - *persist_to_workspace

  # instrumented tests
  test_instrumented:
    <<: *config_gcloud

    steps:
      - *attach_workspace
      - run:
          name: Setup Google Cloud auth
          command: ftl-tests/setup.sh
      - run:
          name: Run tests on Firebase Test Lab
          command: ftl-tests/run-tests.sh
      - run:
          name: Download results
          command: ftl-tests/download-results.sh firebase_test_results
          when: always
      - store_artifacts:
          path: firebase_test_results
      - store_test_results:
          path: firebase_test_results

# orchestrate these multiple jobs, adds dependency between them
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_instrumented:
          requires:
            - build


# =============================================
# original
#
#jobs:
#  build:
#    working_directory: *workspace
#
#    docker:
#      - image: circleci/android:api-27-alpha
#
#    environment:
#      JVM_OPTS: -Xmx3200m
#
#    steps:
#      - checkout
#
#      - restore_cache:
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#
#      - run:
#          name: Download Dependencies
#          command: ./gradlew androidDependencies
#
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#
#      - run:
#          name: Run lint checks
#          command: ./gradlew lint
#
#      - run:
#          name: Run Debug Tests
#          command: ./gradlew testDebug
#
#      - run:
#          name: Run Release Tests
#          command: ./gradlew testRelease
#
#      - store_artifacts:
#          path: app/build/reports
#          destination: reports
#
#      - store_test_results:
#          path: app/build/test-results